// src/styles/ElderlyHomeScreen.styles.js
import { StyleSheet, Platform, StatusBar } from 'react-native';
import { COLORS } from '../constants/theme';

export const getElderlyHomeScreenStyles = (scale = 1.0) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: COLORS.background,
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    scrollContent: {
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 40,
    },
    greetingContainer: {
      marginBottom: Math.round(20 * scale),
    },
    greetingText: {
      fontSize: Math.round(24 * scale),
      fontWeight: '600',
      color: COLORS.textPrimary,
      lineHeight: Math.round(32 * scale),
    },
    greetingName: {
      fontWeight: '800',
      color: COLORS.primary,
    },
    greetingSubtitle: {
      fontSize: Math.round(14 * scale),
      color: COLORS.textSecondary,
      marginTop: 4,
    },
    actionsWrapper: {
      marginBottom: Math.round(24 * scale),
    },
    heroCard: {
      backgroundColor: COLORS.surface,
      borderRadius: 18,
      paddingVertical: Math.round(22 * scale),
      paddingHorizontal: 20,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
      borderWidth: 1.5,
      borderColor: '#E2E8F0',
      minHeight: Math.round(140 * scale),
      ...Platform.select({
        ios: {
          shadowColor: COLORS.primary,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.06,
          shadowRadius: 8,
        },
        android: {
          elevation: 2,
        },
      }),
    },
    heroIconContainer: {
      width: Math.round(72 * scale),
      height: Math.round(72 * scale),
      borderRadius: Math.round(36 * scale),
      backgroundColor: '#EEF2FF',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
      borderWidth: 1,
      borderColor: '#C7D2FE',
    },
    heroCardText: {
      fontSize: Math.round(20 * scale),
      fontWeight: '800',
      color: COLORS.primary,
      textAlign: 'center',
    },
    heroSubtext: {
      fontSize: Math.round(13 * scale),
      color: COLORS.textSecondary,
      marginTop: 3,
      textAlign: 'center',
    },
    gridRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 14,
    },
    gridCard: {
      flex: 1,
      backgroundColor: COLORS.surface,
      borderRadius: 16,
      paddingVertical: Math.round(20 * scale),
      paddingHorizontal: 12,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: '#E2E8F0',
      minHeight: Math.round(130 * scale),
      ...Platform.select({
        ios: {
          shadowColor: COLORS.primary,
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.04,
          shadowRadius: 6,
        },
        android: {
          elevation: 2,
        },
      }),
    },
    gridIconContainer: {
      width: Math.round(54 * scale),
      height: Math.round(54 * scale),
      borderRadius: Math.round(27 * scale),
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    gridCardText: {
      fontSize: Math.round(16 * scale),
      fontWeight: '800',
      color: COLORS.textPrimary,
      textAlign: 'center',
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 14,
    },
    sectionTitle: {
      fontSize: Math.round(22 * scale),
      fontWeight: '800',
      color: COLORS.textPrimary,
      letterSpacing: -0.3,
    },
    sectionBadge: {
      fontSize: Math.round(12 * scale),
      fontWeight: '700',
      color: COLORS.secondary,
      backgroundColor: '#CCFBF1',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
    },
    errorNoticeBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FEF2F2',
      padding: 12,
      borderRadius: 10,
      marginBottom: 12,
      gap: 8,
      borderWidth: 1,
      borderColor: '#FEE2E2',
    },
    errorNoticeText: {
      fontSize: Math.round(13 * scale),
      color: COLORS.danger,
      flex: 1,
      fontWeight: '500',
    },
    visitsList: {
      gap: 12,
    },
    visitCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: COLORS.surface,
      borderRadius: 14,
      minHeight: Math.round(88 * scale),
      paddingVertical: Math.round(12 * scale),
      paddingHorizontal: 8,
      borderWidth: 1.5,
      borderColor: '#E2E8F0',
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.04,
          shadowRadius: 4,
        },
        android: {
          elevation: 2,
        },
      }),
    },
    visitColLeft: {
      flex: 1.1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
    },
    visitDateText: {
      fontSize: Math.round(16 * scale),
      fontWeight: '800',
      color: COLORS.primary,
      textAlign: 'center',
    },
    visitTimeText: {
      fontSize: Math.round(14 * scale),
      fontWeight: '600',
      color: COLORS.textSecondary,
      marginTop: 2,
      textAlign: 'center',
    },
    verticalDivider: {
      width: 1.5,
      height: '65%',
      backgroundColor: '#CBD5E1',
    },
    visitColMiddle: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
    },
    activityIconCircle: {
      width: Math.round(48 * scale),
      height: Math.round(48 * scale),
      borderRadius: Math.round(24 * scale),
      backgroundColor: COLORS.background,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#E2E8F0',
    },
    visitColRight: {
      flex: 1.3,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 4,
    },
    visitCompanionText: {
      fontSize: Math.round(16 * scale),
      fontWeight: '800',
      color: COLORS.textPrimary,
      textAlign: 'center',
    },
    visitStatusText: {
      fontSize: Math.round(12 * scale),
      fontWeight: '600',
      color: COLORS.success,
      marginTop: 2,
    },
    loadingBox: {
      paddingVertical: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    loadingText: {
      marginTop: 12,
      fontSize: Math.round(15 * scale),
      color: COLORS.textSecondary,
      fontWeight: '500',
    },
    emptyCard: {
      backgroundColor: COLORS.surface,
      borderRadius: 16,
      padding: Math.round(26 * scale),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: '#E2E8F0',
      borderStyle: 'dashed',
    },
    emptyTitle: {
      fontSize: Math.round(18 * scale),
      fontWeight: '700',
      color: '#334155',
      marginTop: 12,
    },
    emptySubtitle: {
      fontSize: Math.round(14 * scale),
      color: COLORS.textSecondary,
      textAlign: 'center',
      marginTop: 6,
      lineHeight: Math.round(20 * scale),
    },
    emptyActionBtn: {
      marginTop: 16,
      backgroundColor: COLORS.primary,
      paddingVertical: Math.round(12 * scale),
      paddingHorizontal: 20,
      borderRadius: 10,
      minHeight: Math.round(48 * scale),
      justifyContent: 'center',
      alignItems: 'center',
    },
    emptyActionBtnText: {
      color: '#FFFFFF',
      fontWeight: '700',
      fontSize: Math.round(15 * scale),
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(15, 23, 42, 0.6)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalCard: {
      width: '100%',
      maxWidth: 380,
      backgroundColor: COLORS.background,
      borderRadius: 20,
      padding: 22,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.15,
          shadowRadius: 10,
        },
        android: {
          elevation: 6,
        },
      }),
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#F1F5F9',
      paddingBottom: 10,
    },
    modalTitle: {
      fontSize: Math.round(20 * scale),
      fontWeight: '800',
      color: COLORS.primary,
    },
    modalBody: {
      gap: 12,
    },
    detailRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    detailLabel: {
      fontSize: Math.round(15 * scale),
      fontWeight: '600',
      color: COLORS.textSecondary,
    },
    detailValue: {
      fontSize: Math.round(15 * scale),
      fontWeight: '700',
      color: COLORS.textPrimary,
    },
    modalCloseBtn: {
      backgroundColor: COLORS.primary,
      borderRadius: 12,
      paddingVertical: 14,
      alignItems: 'center',
      marginTop: 14,
      minHeight: Math.round(48 * scale),
      justifyContent: 'center',
    },
    modalCloseBtnText: {
      color: '#FFFFFF',
      fontSize: Math.round(16 * scale),
      fontWeight: '700',
    },
  });

export default getElderlyHomeScreenStyles(1.0);
