// src/styles/MyScheduleScreen.styles.js
import { StyleSheet, Platform, StatusBar } from 'react-native';
import { COLORS } from '../constants/theme';

export const getMyScheduleScreenStyles = (scale = 1.0) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: '#1A365D',
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    container: {
      flex: 1,
      backgroundColor: '#F8FAFC',
    },

    // WhatsApp-Style Top App Header
    headerBar: {
      backgroundColor: '#1A365D',
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 4,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    backButton: {
      padding: 6,
      borderRadius: 20,
    },
    headerTitle: {
      fontSize: Math.round(20 * scale),
      fontWeight: '800',
      color: '#FFFFFF',
      letterSpacing: -0.2,
    },
    headerRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    headerActionBtn: {
      padding: 8,
      borderRadius: 20,
    },

    // WhatsApp-Style Tabs Bar
    tabsBarWrapper: {
      backgroundColor: '#1A365D',
      borderBottomWidth: 1,
      borderBottomColor: '#2A4365',
    },
    tabsBarScrollContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 8,
      minWidth: '100%',
    },
    tabItem: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 14,
      paddingHorizontal: 4,
      position: 'relative',
      gap: 4,
    },
    tabText: {
      fontSize: Math.round(11.5 * scale),
      fontWeight: '800',
      color: '#94A3B8',
      letterSpacing: 0.2,
      textTransform: 'uppercase',
      textAlign: 'center',
    },
    tabTextActive: {
      color: '#FFFFFF',
      fontWeight: '900',
    },
    tabBadge: {
      backgroundColor: '#38BDF8',
      borderRadius: 9,
      paddingHorizontal: 5,
      paddingVertical: 1,
      minWidth: 18,
      height: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabBadgeText: {
      fontSize: Math.round(10 * scale),
      fontWeight: '900',
      color: '#0F172A',
    },
    tabActiveIndicator: {
      position: 'absolute',
      bottom: 0,
      left: 4,
      right: 4,
      height: 3,
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 3,
      borderTopRightRadius: 3,
    },

    // List Content Container
    listContent: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 40,
    },

    // Schedule Cards
    card: {
      backgroundColor: '#FFFFFF',
      borderRadius: 18,
      padding: 16,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      ...Platform.select({
        ios: {
          shadowColor: '#1A365D',
          shadowOffset: { width: 0, height: 3 },
          shadowOpacity: 0.06,
          shadowRadius: 6,
        },
        android: {
          elevation: 2,
        },
      }),
    },
    cardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    cardActivityRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      flex: 1,
    },
    activityIconBox: {
      width: Math.round(44 * scale),
      height: Math.round(44 * scale),
      borderRadius: Math.round(22 * scale),
      backgroundColor: '#EEF2FF',
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#C7D2FE',
    },
    activityTitleWrap: {
      flex: 1,
    },
    activityTitle: {
      fontSize: Math.round(17 * scale),
      fontWeight: '800',
      color: '#0F172A',
      letterSpacing: -0.2,
    },
    companionSubtitle: {
      fontSize: Math.round(13 * scale),
      color: '#64748B',
      marginTop: 2,
      fontWeight: '600',
    },

    // Status Badges
    statusBadge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statusPending: {
      backgroundColor: '#FEF3C7',
    },
    statusPendingText: {
      color: '#B45309',
      fontSize: Math.round(11 * scale),
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    statusAccepted: {
      backgroundColor: '#DCFCE7',
    },
    statusAcceptedText: {
      color: '#15803D',
      fontSize: Math.round(11 * scale),
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    statusOngoing: {
      backgroundColor: '#DBEAFE',
    },
    statusOngoingText: {
      color: '#1D4ED8',
      fontSize: Math.round(11 * scale),
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    statusCompleted: {
      backgroundColor: '#F1F5F9',
    },
    statusCompletedText: {
      color: '#475569',
      fontSize: Math.round(11 * scale),
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    statusCancelled: {
      backgroundColor: '#FEE2E2',
    },
    statusCancelledText: {
      color: '#B91C1C',
      fontSize: Math.round(11 * scale),
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    statusExpired: {
      backgroundColor: '#FFEDD5',
      borderWidth: 1,
      borderColor: '#FED7AA',
    },
    statusExpiredText: {
      color: '#C2410C',
      fontSize: Math.round(11 * scale),
      fontWeight: '800',
      textTransform: 'uppercase',
    },

    // Card Details Row
    cardDetailsBox: {
      backgroundColor: '#F8FAFC',
      borderRadius: 12,
      paddingVertical: 10,
      paddingHorizontal: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      gap: 6,
    },
    detailRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    detailText: {
      fontSize: Math.round(14 * scale),
      color: '#1E293B',
      fontWeight: '700',
    },

    // Comm Method Badge
    commBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      alignSelf: 'flex-start',
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      marginTop: 2,
    },
    commBadgeText: {
      fontSize: Math.round(12 * scale),
      color: '#334155',
      fontWeight: '700',
      textTransform: 'capitalize',
    },

    // Communication Action Strip
    commActionStrip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 10,
      paddingVertical: 4,
    },
    primaryCommBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 9,
      paddingHorizontal: 14,
      borderRadius: 10,
      backgroundColor: '#0284C7',
      elevation: 1,
      shadowColor: '#0284C7',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.15,
      shadowRadius: 2,
    },
    primaryCommBtnText: {
      fontSize: Math.round(13 * scale),
      fontWeight: '800',
      color: '#FFFFFF',
    },
    switchMethodBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      paddingVertical: 9,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: '#F1F5F9',
      borderWidth: 1,
      borderColor: '#CBD5E1',
    },
    switchMethodBtnText: {
      fontSize: Math.round(12 * scale),
      fontWeight: '800',
      color: '#334155',
    },

    // Card Actions
    cardActionsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: '#F1F5F9',
      gap: 8,
    },
    actionButtonsGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    detailsBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 7,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: '#EEF2FF',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#C7D2FE',
    },
    detailsBtnText: {
      fontSize: Math.round(12 * scale),
      fontWeight: '800',
      color: '#1A365D',
    },
    editBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 7,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: '#F0F9FF',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#BAE6FD',
    },
    editBtnText: {
      fontSize: Math.round(12 * scale),
      fontWeight: '800',
      color: '#0284C7',
    },
    deleteBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 7,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: '#FEF2F2',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#FECACA',
    },
    deleteBtnText: {
      fontSize: Math.round(12 * scale),
      fontWeight: '800',
      color: '#DC2626',
    },
    startVisitBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 7,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: '#EFF6FF',
      justifyContent: 'center',
      borderWidth: 1.2,
      borderColor: '#3B82F6',
    },
    startVisitBtnDisabled: {
      backgroundColor: '#F1F5F9',
      borderColor: '#CBD5E1',
      opacity: 0.65,
    },
    startVisitBtnText: {
      fontSize: Math.round(12 * scale),
      fontWeight: '800',
      color: '#1D4ED8',
    },
    startVisitBtnTextDisabled: {
      color: '#94A3B8',
    },
    completeVisitBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 7,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: '#ECFDF5',
      justifyContent: 'center',
      borderWidth: 1.2,
      borderColor: '#10B981',
    },
    completeVisitBtnText: {
      fontSize: Math.round(12 * scale),
      fontWeight: '800',
      color: '#047857',
    },
    cancelBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 7,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: '#FEF2F2',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#FECACA',
    },
    cancelBtnText: {
      fontSize: Math.round(12 * scale),
      fontWeight: '800',
      color: '#DC2626',
    },
    rateVisitBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingVertical: 7,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: '#FEF3C7',
      justifyContent: 'center',
      borderWidth: 1.2,
      borderColor: '#F59E0B',
    },
    rateVisitBtnText: {
      fontSize: Math.round(12 * scale),
      fontWeight: '800',
      color: '#B45309',
    },
    ratedBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingVertical: 7,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: '#F1F5F9',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#CBD5E1',
    },
    ratedBtnText: {
      fontSize: Math.round(12 * scale),
      fontWeight: '800',
      color: '#475569',
    },

    // Empty State
    emptyContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 60,
      paddingHorizontal: 30,
    },
    emptyIconCircle: {
      width: Math.round(80 * scale),
      height: Math.round(80 * scale),
      borderRadius: Math.round(40 * scale),
      backgroundColor: '#EEF2FF',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
      borderWidth: 1,
      borderColor: '#C7D2FE',
    },
    emptyTitle: {
      fontSize: Math.round(18 * scale),
      fontWeight: '800',
      color: '#1A365D',
      marginBottom: 6,
      textAlign: 'center',
    },
    emptySubtitle: {
      fontSize: Math.round(14 * scale),
      color: '#64748B',
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: 20,
    },
    emptyActionBtn: {
      backgroundColor: '#1A365D',
      paddingVertical: 12,
      paddingHorizontal: 22,
      borderRadius: 14,
      shadowColor: '#1A365D',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 6,
      elevation: 3,
    },
    emptyActionBtnText: {
      color: '#FFFFFF',
      fontSize: Math.round(14 * scale),
      fontWeight: '800',
    },

    // Modal Details Sheet
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(15, 23, 42, 0.6)',
      justifyContent: 'flex-end',
    },
    modalSheet: {
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 22,
      paddingTop: 20,
      paddingBottom: Platform.OS === 'ios' ? 34 : 24,
      maxHeight: '80%',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#F1F5F9',
      paddingBottom: 12,
    },
    modalTitle: {
      fontSize: Math.round(19 * scale),
      fontWeight: '900',
      color: '#1A365D',
    },
    modalCloseBtn: {
      padding: 4,
    },
    modalRow: {
      marginBottom: 12,
    },
    modalLabel: {
      fontSize: Math.round(12 * scale),
      fontWeight: '800',
      color: '#64748B',
      textTransform: 'uppercase',
      marginBottom: 2,
    },
    modalValue: {
      fontSize: Math.round(15 * scale),
      fontWeight: '700',
      color: '#0F172A',
    },
    modalNotesBox: {
      backgroundColor: '#F8FAFC',
      borderRadius: 12,
      padding: 12,
      borderWidth: 1,
      borderColor: '#E2E8F0',
      marginTop: 4,
    },

    // Communication Switcher Sheet Styles
    commModalSheet: {
      backgroundColor: '#FFFFFF',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: Platform.OS === 'ios' ? 36 : 24,
    },
    commOptionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 14,
      backgroundColor: '#F8FAFC',
      borderWidth: 1.5,
      borderColor: '#E2E8F0',
      marginBottom: 10,
      gap: 12,
    },
    commOptionItemActive: {
      backgroundColor: '#EFF6FF',
      borderColor: '#3B82F6',
    },
    commOptionIconCircle: {
      width: Math.round(44 * scale),
      height: Math.round(44 * scale),
      borderRadius: Math.round(22 * scale),
      alignItems: 'center',
      justifyContent: 'center',
    },
    commOptionTextWrap: {
      flex: 1,
    },
    commOptionTitle: {
      fontSize: Math.round(15 * scale),
      fontWeight: '800',
      color: '#0F172A',
      marginBottom: 2,
    },
    commOptionSubtitle: {
      fontSize: Math.round(12 * scale),
      color: '#64748B',
      fontWeight: '600',
    },
    commActivePill: {
      backgroundColor: '#DCFCE7',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 8,
    },
    commActivePillText: {
      fontSize: Math.round(10 * scale),
      fontWeight: '800',
      color: '#15803D',
      textTransform: 'uppercase',
    },

    // Video Calling Modal Styles
    videoBackdrop: {
      flex: 1,
      backgroundColor: '#0F172A',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: Platform.OS === 'ios' ? 60 : 40,
      paddingHorizontal: 24,
    },
    videoTopHeader: {
      alignItems: 'center',
      gap: 6,
    },
    videoHeaderBadge: {
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      paddingHorizontal: 14,
      paddingVertical: 5,
      borderRadius: 20,
    },
    videoHeaderBadgeText: {
      color: '#E2E8F0',
      fontSize: Math.round(12 * scale),
      fontWeight: '700',
    },
    videoCenterContent: {
      alignItems: 'center',
      gap: 12,
    },
    videoAvatarOuter: {
      width: Math.round(120 * scale),
      height: Math.round(120 * scale),
      borderRadius: Math.round(60 * scale),
      backgroundColor: 'rgba(59, 130, 246, 0.2)',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: '#3B82F6',
    },
    videoCallerName: {
      color: '#FFFFFF',
      fontSize: Math.round(22 * scale),
      fontWeight: '900',
    },
    videoCallStatus: {
      color: '#93C5FD',
      fontSize: Math.round(14 * scale),
      fontWeight: '600',
    },
    videoControlsContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 20,
      width: '100%',
    },
    videoControlBtn: {
      width: Math.round(56 * scale),
      height: Math.round(56 * scale),
      borderRadius: Math.round(28 * scale),
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    videoEndBtn: {
      width: Math.round(64 * scale),
      height: Math.round(64 * scale),
      borderRadius: Math.round(32 * scale),
      backgroundColor: '#EF4444',
      alignItems: 'center',
      justifyContent: 'center',
      elevation: 6,
    },
    volunteerProfileCard: {
      backgroundColor: '#EFF6FF',
      borderRadius: 14,
      padding: 12,
      borderWidth: 1,
      borderColor: '#BFDBFE',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 4,
    },
    volunteerCardLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      flex: 1,
    },
    volunteerAvatarMini: {
      width: Math.round(38 * scale),
      height: Math.round(38 * scale),
      borderRadius: Math.round(19 * scale),
      backgroundColor: '#DBEAFE',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: '#3B82F6',
    },
    volunteerCardName: {
      fontSize: Math.round(14 * scale),
      fontWeight: '800',
      color: '#1E3A8A',
    },
    volunteerCardSub: {
      fontSize: Math.round(11.5 * scale),
      color: '#2563EB',
      fontWeight: '600',
    },
    viewProfileLinkBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#2563EB',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 10,
      gap: 4,
    },
    viewProfileLinkText: {
      color: '#FFFFFF',
      fontSize: Math.round(11.5 * scale),
      fontWeight: '700',
    },
    ratingSummarySection: {
      backgroundColor: '#FFFBEB',
      borderRadius: 14,
      padding: 14,
      borderWidth: 1,
      borderColor: '#FDE68A',
      marginTop: 8,
      gap: 8,
    },
    ratingSummaryHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    ratingSummaryTitle: {
      fontSize: Math.round(13.5 * scale),
      fontWeight: '800',
      color: '#92400E',
    },
    ratingItemRow: {
      gap: 3,
    },
    ratingItemLabel: {
      fontSize: Math.round(12 * scale),
      fontWeight: '700',
      color: '#78350F',
    },
    ratingStarsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
    },
    ratingFeedbackText: {
      fontSize: Math.round(12.5 * scale),
      color: '#451A03',
      fontStyle: 'italic',
      marginTop: 2,
    },
  });
