// src/styles/ProfileScreen.styles.js
import { StyleSheet, Platform, StatusBar } from 'react-native';
import { COLORS } from '../constants/theme';

export const getProfileScreenStyles = (scale = 1.0) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
    },
    topBar: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 14,
    },
    circleButton: {
      width: Math.round(44 * scale),
      height: Math.round(44 * scale),
      borderRadius: Math.round(22 * scale),
      borderWidth: 1.5,
      borderColor: '#000000',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
    },
    closeButton: {
      padding: 6,
      justifyContent: 'center',
      alignItems: 'center',
    },
    scrollContainer: {
      paddingHorizontal: 24,
      paddingBottom: 40,
    },
    avatarSection: {
      alignItems: 'center',
      marginTop: 8,
      marginBottom: Math.round(20 * scale),
    },
    avatarWrapper: {
      position: 'relative',
    },
    avatarPlaceholder: {
      width: Math.round(150 * scale),
      height: Math.round(150 * scale),
      borderRadius: Math.round(75 * scale),
      backgroundColor: '#D9D9D9',
      justifyContent: 'center',
      alignItems: 'center',
    },
    avatarImage: {
      width: Math.round(150 * scale),
      height: Math.round(150 * scale),
      borderRadius: Math.round(75 * scale),
      backgroundColor: '#E2E8F0',
    },
    cameraBadge: {
      position: 'absolute',
      bottom: 4,
      right: 4,
      width: Math.round(36 * scale),
      height: Math.round(36 * scale),
      borderRadius: Math.round(18 * scale),
      backgroundColor: COLORS.primary,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: '#FFFFFF',
    },
    userTitle: {
      fontSize: Math.round(20 * scale),
      fontWeight: '800',
      color: '#000000',
      marginTop: 14,
    },
    badgesRow: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      marginVertical: Math.round(14 * scale),
      paddingHorizontal: 16,
    },
    badgeCol: {
      alignItems: 'center',
    },
    badgeIconBox: {
      marginBottom: 4,
      alignItems: 'center',
      justifyContent: 'center',
    },
    badgeLabel: {
      fontSize: Math.round(16 * scale),
      fontWeight: '700',
    },
    dividerLine: {
      height: 1.5,
      backgroundColor: '#1E293B',
      marginVertical: Math.round(18 * scale),
    },
    sectionBlock: {
      marginVertical: 4,
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    sectionTitle: {
      fontSize: Math.round(22 * scale),
      fontWeight: '800',
      color: '#000000',
      letterSpacing: -0.3,
    },
    editIconBtn: {
      padding: 4,
    },
    detailsContent: {
      gap: Math.round(8 * scale),
    },
    detailLine: {
      fontSize: Math.round(17 * scale),
      color: '#000000',
      lineHeight: Math.round(26 * scale),
    },
    detailBold: {
      fontWeight: '800',
      color: '#000000',
    },
    interestsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 16,
      marginTop: 8,
    },
    interestItem: {
      alignItems: 'center',
    },
    interestCircle: {
      width: Math.round(74 * scale),
      height: Math.round(74 * scale),
      borderRadius: Math.round(37 * scale),
      backgroundColor: '#D9D9D9',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 6,
    },
    interestLabel: {
      fontSize: Math.round(15 * scale),
      fontWeight: '700',
      color: '#000000',
    },
    // Display / Size selector row
    sizeSelectorRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#F8FAFC',
      padding: Math.round(12 * scale),
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: '#E2E8F0',
      marginTop: 8,
    },
    sizeSelectorLabel: {
      fontSize: Math.round(16 * scale),
      fontWeight: '700',
      color: COLORS.textPrimary,
    },
    sizeButtonsGroup: {
      flexDirection: 'row',
      gap: 8,
    },
    sizePill: {
      paddingVertical: Math.round(6 * scale),
      paddingHorizontal: Math.round(14 * scale),
      borderRadius: 10,
      backgroundColor: '#E2E8F0',
      borderWidth: 1,
      borderColor: '#CBD5E1',
    },
    sizePillActive: {
      backgroundColor: COLORS.primary,
      borderColor: COLORS.primary,
    },
    sizePillText: {
      fontSize: Math.round(14 * scale),
      fontWeight: '700',
      color: COLORS.textPrimary,
    },
    sizePillTextActive: {
      color: '#FFFFFF',
    },
    menuBlock: {
      marginVertical: 4,
    },
    menuItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
    },
    menuItemText: {
      fontSize: Math.round(18 * scale),
      fontWeight: '700',
      color: '#000000',
      includeFontPadding: false,
      textAlignVertical: 'center',
    },
    menuItemIconBox: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    logoutButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      backgroundColor: '#FEF2F2',
      borderWidth: 1.5,
      borderColor: '#FECACA',
      borderRadius: 14,
      paddingVertical: Math.round(15 * scale),
      marginTop: 12,
      marginBottom: 20,
    },
    logoutButtonText: {
      fontSize: Math.round(17 * scale),
      fontWeight: '800',
      color: COLORS.danger,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(15, 23, 42, 0.6)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalSheet: {
      width: '90%',
      maxWidth: 340,
      backgroundColor: '#FFFFFF',
      borderRadius: 20,
      padding: 20,
      alignItems: 'center',
    },
    sheetTitle: {
      fontSize: Math.round(18 * scale),
      fontWeight: '800',
      color: COLORS.primary,
      marginBottom: 16,
    },
    sheetBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      width: '100%',
      paddingVertical: 14,
    },
    sheetBtnText: {
      fontSize: Math.round(16 * scale),
      fontWeight: '700',
      color: COLORS.textPrimary,
    },
    sheetCancelBtn: {
      marginTop: 10,
      paddingVertical: 10,
    },
    sheetCancelBtnText: {
      fontSize: Math.round(15 * scale),
      fontWeight: '700',
      color: COLORS.textSecondary,
    },
    modalCard: {
      width: '100%',
      maxWidth: 380,
      backgroundColor: '#FFFFFF',
      borderRadius: 20,
      padding: 22,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    modalTitle: {
      fontSize: Math.round(20 * scale),
      fontWeight: '800',
      color: COLORS.primary,
    },
    formGroup: {
      marginBottom: 14,
    },
    inputLabel: {
      fontSize: Math.round(14 * scale),
      fontWeight: '700',
      color: COLORS.textSecondary,
      marginBottom: 6,
    },
    textInput: {
      height: Math.round(50 * scale),
      backgroundColor: '#F8FAFC',
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: '#E2E8F0',
      paddingHorizontal: 14,
      fontSize: Math.round(16 * scale),
      color: COLORS.textPrimary,
    },
    readOnlyInput: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#F1F5F9',
    },
    readOnlyText: {
      fontSize: Math.round(15 * scale),
      color: '#64748B',
      fontWeight: '600',
    },
    modalBtnRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 12,
      marginTop: 16,
    },
    cancelBtn: {
      paddingVertical: Math.round(12 * scale),
      paddingHorizontal: 18,
      borderRadius: 10,
    },
    cancelBtnText: {
      fontSize: Math.round(15 * scale),
      fontWeight: '700',
      color: COLORS.textSecondary,
    },
    saveBtn: {
      backgroundColor: COLORS.primary,
      paddingVertical: Math.round(12 * scale),
      paddingHorizontal: 22,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    saveBtnText: {
      color: '#FFFFFF',
      fontSize: Math.round(15 * scale),
      fontWeight: '700',
    },
    interestsHint: {
      fontSize: Math.round(14 * scale),
      color: COLORS.textSecondary,
      marginBottom: 16,
      lineHeight: Math.round(20 * scale),
    },
    interestsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 14,
    },
    interestChoicePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: Math.round(10 * scale),
      paddingHorizontal: Math.round(14 * scale),
      borderRadius: 20,
      backgroundColor: '#F1F5F9',
      borderWidth: 1.5,
      borderColor: '#E2E8F0',
    },
    interestChoicePillSelected: {
      backgroundColor: COLORS.primary,
      borderColor: COLORS.primary,
    },
    pillIconBox: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    interestChoiceText: {
      fontSize: Math.round(14 * scale),
      fontWeight: '700',
      color: COLORS.textPrimary,
    },
    interestChoiceTextSelected: {
      color: '#FFFFFF',
    },
  });

export default getProfileScreenStyles(1.0);
